<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>CardEngine.Runner</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CardEngine.Core/CardEngine.Core.csproj" />
    <ProjectReference Include="../CardEngine.AI/CardEngine.AI.csproj" />
    <ProjectReference Include="../CardEngine.Serialization/CardEngine.Serialization.csproj" />
  </ItemGroup>
</Project>
